---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bloodapp-resource-quota
spec:
  hard:
    pods: "6"
    requests.cpu: "1"
    requests.memory: 50Mbi
    limits.cpu: "2"
    limits.memory: 1Gi
